### your site title here

title: Danniell Hu
description: Computer Science PhD Student @ UMich

baseurl: ""
# url: /dannihu01.github.io #name of GitHub repository
# url: "" #custom url to be used instead of GitHub repository
email: #

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
# twitter: "#"
linkedin: "https://www.linkedin.com/in/danniell-hu/"
# stackoverflow: "#"
github: "https://github.com/Dannihu01"
# researchgate: "#"
orcid: "https://orcid.org/0009-0000-1868-3004"
# quora: "#"
instagram: "https://www.instagram.com/dannihu01/?locale=en-US"
# facebook: "#"

# custom variables
author_name: "Danniell Hu"


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  publications:
    output: true
    permalink: /publications/:name/
  news:
    output: true
    permalink: /news/:name/
  # projects:
  #   output: true
  #   permalink: /projects/:name/
  #   order:
  #     - shortProject.md
  #     - longerProjectTitle.md
  #     - redirect.md
  #     - project4.md
  #     - project5.md
  #     - project6.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank

